name 'puppet-module-postfix'
version '1.0.0'
source 'git://github.com:Phil-Friderici/puppet-module-postfix.git'
author 'Phil-Friderici'
license 'Apache License, Version 2.0'
summary 'Manage Postfix mail relaying'
description 'Manage Postfix'
project_page 'https://github.com/Phil-Friderici/puppet-module-postfix'
dependency 'puppetlabs/stdlib', '>= 3.2.0'
